---
version: 3

vars:
  INFRA_NAMESPACE: infra

tasks:
## Templates for Helm and Kubectl operations
  helm:repo-install:
    desc: Install Helm charts from repo
    cmds:
      - helm repo add {{.name}} {{.url}}
      - helm repo update
      - | 
        helm upgrade --install "{{.name}}" "{{.name}}/{{.name}}" \
        --version "{{.version}}" \
        -n "{{.INFRA_NAMESPACE}}" \
        --create-namespace \
        -f {{.vars_file}}" \
  helm:uninstall:
    desc: Uninstall Helm chart
    cmds:
      - helm uninstall {{.name}} -n {{.INFRA_NAMESPACE}}
  kubectl:apply:
    desc: Apply Kubernetes manifest
    cmds:
      - kubectl apply -f {{.manifest_file}} -n {{.INFRA_NAMESPACE}}
  kubectl:delete:
    desc: Delete Kubernetes manifest
    cmds:
      - kubectl delete -f {{.manifest_file}} -n {{.INFRA_NAMESPACE}}

## TLS Secrets
  tls:install:
      desc: Install Kubernetes TLS secrets
      cmds:
        - kubectl create secret tls versaliminal-tls --cert=config/tls/versaliminal-entity.crt --key=config/tls/versaliminal-entity.key --namespace=infra
  tls:uninstall:
    desc: Uninstall Kubernetes TLS secrets
    cmds:
      - kubectl delete secret versaliminal-tls --namespace=infra

## PrivateBin
  privatebin:install:
    desc: Install PrivateBin
    cmds:
      - task: k8s:helm:repo-install
        url: https://privatebin.github.io/helm-chart
        name: privatebin
        vars_file: privatebin/vars.yaml
        version: 0.23.3
  privatebin:uninstall:
    desc: Uninstall PrivateBin
    cmds:
      - task: helm:uninstall
        vars:
          name: privatebin
      - task: kubectl:delete
        vars:
          manifest_file: privatebin/ingressroute.yaml
          

## Traefik
  traefik:install:
    desc: Install upstream Helm chart for Traefik with Gateway API
    cmds:
      - task: kubectl:apply
        vars:
          manifest_file: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
      - task: kubectl:apply
        vars:
          manifest_file: https://raw.githubusercontent.com/traefik/traefik/v3.5/docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml
      - task: helm:repo-install
        vars:
          url: https://traefik.github.io/charts
          name: traefik
          vars_file: traefik/vars.yaml
          version: v35.0.1
      - task: kubectl:apply
        vars:
          manifest_file: traefik/gateway.yaml
  traefik:uninstall:
    desc: Uninstall traefik
    cmds:
      - task: helm:uninstall
        vars:
          name: traefik
      - task: kubectl:delete
        vars:
          manifest_file: traefik/gateway.yaml
      