---
version: 3

includes:
  k8s:
    taskfile: config/kubernetes/taskfile.yaml
    dir: config/kubernetes
  talos:
    taskfile: config/talos/taskfile.yaml
    dir: config/talos
  ssh:
    taskfile: config/ssh/taskfile.yaml
    dir: config/ssh
  tls:
    taskfile: config/tls/taskfile.yaml
    dir: config/tls

tasks:
  init:
    desc: Initialize repository state
    cmds:
      - task private-files:unarchive
      - python3 -m venv .venv
      - .venv/bin/python3 -m pip install -r scripts/requirements.txt
      - .venv/bin/python3 scripts/invutil.py --env

  archive:
    desc: Archive lab files
    vars:
      tar_file: lab.tar.zst
    cmds:
      - tar --zstd -vf {{.tar_file}} --exclude .venv  --exclude *.tar* -c .
      
  private-files:archive:
    desc: Archive private lab files
    vars:
      tar_file: lab-private.tar.zst
    cmds:
      - tar --zstd -vf {{.tar_file}} -c config/ssh config/talos/ config/tls inventory.private.yaml
      - gpg --symmetric --cipher-algo AES256 {{.tar_file}}
      - rm {{.tar_file}}
  private-files:unarchive:
    desc: Unarchive private lab files
    vars:
      tar_file: lab-private.tar.zst
    cmds:
      - gpg --decrypt -o {{.tar_file}} {{.tar_file}}.gpg
      - tar --zstd -xvf {{.tar_file}}
      - rm {{.tar_file}}